name: Ma première CI/CD

on:
  push:
    branches: [main]
    tags:
     - git tag -a v1.0 -m "Mon message de version"

jobs:
  security-and-build:
    # On utilise l'Ubuntu latest pour la build
    runs-on: ubuntu-latest

    steps:
      # On récupère le code via le git
      - uses: actions/checkout@v3
      # On utilise/install Node.js 20.x
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      # On installe les dépendances
      - run: npm ci
      # On lance le linter
      - run: npm run lint
      # On lance les tests
      - run: npm test

      #SCA
      - name: SCA - Audit des dépendances
        run: npm audit --audit-level=high
      #SAST
      - name: SAST - Scan du code source (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript
      #Notification discord
      - name: Notify d'échec (Discord)
        if: failure()
        run: |
          echo "### ❌ Échec de la Pipelinede Sécurité" >> $GITHUB_STEP_SUMMARY
          echo "Une vulnérabilité ou un bug a été détecté. Vérifiez les logs SAST/SCA." >> $GITHUB_STEP_SUMMARY

          # Envoi d'un Webhook Discord
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "CI/CD Bot",
            "embeds": [{
              "title": "❌ Pipeline échouée : ça marche pas"
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: security-and-build
    runs-on: ubuntu-latest
    if : github.ref == 'refs/heads/main' # On ne déploie que depuis la branche main
    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.API_KEY }}
          service-id: ${{ secrets.SECRET_KEY }}
          discord-webhook : ${{ secrets.DISCORD_WEBHOOK }}
      

